// import AntdFormPage from "@/components/AntdForm";
import Head from "next/head";
// import ShipmentPage from "./shipment-page";
// import DynamicForm from "./dynamic-form";
import { useState, useEffect } from "react";
import Pagination from "../components/Pagination";
export default function Home(pageName: unknown) {
  const [currentPage, setCurrentPage] = useState(1);
  const totalPages = 10; // You would set this based on your data

  const onPageChange = (page: number) => {
    setCurrentPage(page);
    // You would typically fetch data for the new page here
  };

  useEffect(() => {
    // Update the body class when the component mounts
    document.body.className = `page-${pageName}`;
    return () => {
      // Reset the body class when the component unmounts
      document.body.className = "";
    };
  }, [pageName]);

  return (
    <>
      <Head>
        <title>Antd FormPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          onPageChange={onPageChange}
        />

        {/* <ShipmentPage /> */}

        {/* <DynamicForm/> */}

        {/* <AntdFormPage /> */}
      </main>
    </>
  );
}
